# Site settings
title: Cloud Computing Infrastructure
description: >-
  Comprehensive notes for COE505 - Cloud Computing Infrastructure
  MSc. Machine Learning Program @ American University of Sharjah
baseurl: "/Cloud-Computing-Infrastructure"
url: "https://daravaram.github.io"

# Author information
author:
  name: Dara Varam
  email: dara@example.com

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation menu
header_pages:
  - index.md
  - lectures.md
  - ai-notes.md
  - mcqs.md

# Collections
collections:
  lectures:
    output: true
    permalink: /:collection/:name/
  ai_notes:
    output: true
    permalink: /:collection/:name/

# Default settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "lectures"
    values:
      layout: "lecture"
  - scope:
      path: ""
      type: "ai_notes"
    values:
      layout: "lecture"

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _pages

# Markdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# SEO settings
google_analytics: # Add your GA tracking ID if you have one